### ISSUE TITLE
README.md换行

### ISSUE THREAD

**Issue by PhoenixHe-NV** [jackyyf/paste.py#7]
如果可以的话麻烦README.md每行不超过70字母...

**Comment by jackyyf** [comment]
等我回家回去改……不过估计只能做到markdown源码wrap到72，网页显示如果wrap到72显示效果很差。。

**Comment by Endle** [comment]
@htc550605125  好奇的问一句，markdown 的宽度控制到 70 是为了什么？算不算行尾的两个空格？

**Comment by jackyyf** [comment]
看了看很多地方没有办法wrap到72字符.. 比如
`[]()`这种markdown中的链接格式完全没有办法分成两行

只能尽量做到能wrap的地方wrap一下了
